- Makefile
- uhubctl.c
This pull request makes uhubctl "Yocto-Project Compatible" and therefore adds cross-compile compatibility to the Makefile.
Changes v2:
- set `LDFLAGS` only on Linux based OSes (detect that using `uname`)
- use `-rf` for `RM`
> Make uhubctl "Yocto-Project Compatible" v2

- uhubctl.c
Since libusb version 1.0.16 the libusb_get_port_path function is
deprecated. As we need to support also older version of libusb we
replace it with libusb_get_port_numbers when possible. This is done by
checking the LIBUSB_API_VERSION (as recommended by libusb).
Signed-off-by: Richard Leitner <richard.leitner@skidata.com>
> uhubctl: avoid deprecated libusb_get_port_path

- README.md
Furthermore add the Lenovo ThinkPad EU Ultra Dockingstation (40A20090EU)
as a supported device.
Signed-off-by: Richard Leitner <richard.leitner@skidata.com>
> README: format supported devices as table and add USB VID/PID

- uhubctl.c
Relating to #25, this adds an option to reset the hub after powering on a device, causing all devices to re-associate.
AFAIK it does not make sense to reset the hub after powering off a device, because it just comes back.
> add option to reset hub after turning device on

- Formula/uhubctl.rb
- README.md
I've added comment how to install uhubctl using homebrew. Formula from https://github.com/Homebrew/homebrew-head-only/pull/172
> Mac homebrew installation

- README.md
- README.md updated to reflect the 'B&B Electronics' rebranding as 'B+B SmartWorx'
- updated B+B UHR204 with VID:PID
- added B+B USH304 hub details
> Update company name and add another compatible hub

- uhubctl.c
Thank you for your excellent work. This program is very helpful.
Scenario:
In my usage, I have two identical hubs. 
host -> hub1 -> hub2 -> device
I want to control the port of the second hub, while I don't care which port of the first hub was used.
In this usage, I need to use a script to find the port and create the -l part. With the change, It is as easy as
```uhubctl -L 3```
Also, I think this level info is helpful for the dual match. I'm using nvidia TX2, which 
the usb3 port is assigned as 1-2
and the usb2 port is 2-1
The program was confused between the two hubs.
> add a level hub filter

- uhubctl.c
```
$ make
cc  -g -O0 -Wall -Wextra -std=c99 -pedantic -DPROGRAM_VERSION=\"v2.1.0-11-g39b407a8\" uhubctl.c -o uhubctl -Wl,-zrelro,-znow -lusb-1.0
uhubctl.c: In function ‘get_device_description’:
uhubctl.c:543:31: warning: ‘%s’ directive output may be truncated writing up to 63 bytes into a region of size between 58 and 247 [-Wformat-truncation=]
"%04x:%04x%s%s%s%s%s%s%s",
^~
uhubctl.c:548:9:
ports
~~~~~                  
uhubctl.c:542:5: note: ‘snprintf’ output 10 or more bytes (assuming 262) into a destination of size 256
snprintf(ds->description, sizeof(ds->description),
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"%04x:%04x%s%s%s%s%s%s%s",
~~~~~~~~~~~~~~~~~~~~~~~~~~
id_vendor, id_product,
~~~~~~~~~~~~~~~~~~~~~~
ds->vendor[0]  ? " " : "", ds->vendor, …
```
> Fix compile warning about format truncation by increasing buffer size

- uhubctl_git.bb
The license copyright year was updated but the yocto/bitbake recipe was not updated.  This commit brings them both in sync, just in time for 2020.  :-)
> Update license hash to correct value, fixing yocto building

- Makefile
This PR let me build on OmniOS and OpenIndiana with libusb-1.0 - but neither build saw a smart hub.
> Makefile: add support for "SunOS" (e.g. with modern illumos)

- uhubctl.c
@sre, @jfberry: this PR should fix (or at least considerably improve) device correlation problem #248.
Can you please try it?
```
git clone https://github.com/mvp/uhubctl -b usb3-duality
make
./uhubctl -l {path}
```
It should do matching almost always correctly.
However, it may still fail if you connect 2+ completely identical hubs (with the same container IDs), but even this should work correctly if you daisy-chain them.
If you confirm that it works for you, I will merge it to master branch.
> Improve USB2/3 duality matching

- uhubctl.c
This fixes UB. 
Before:
```
> uhubctl -l 012345678901234567890123456789012 -s bar
There were permission problems while accessing USB.
Follow https://git.io/JIB2Z for a fix!
No compatible devices detected at location 01234567890123456789012345678901bar!
Run with -h to get usage info.
```
After:
```
> uhubctl -l 012345678901234567890123456789012 -s bar
There were permission problems while accessing USB.
Follow https://git.io/JIB2Z for a fix!
No compatible devices detected at location 01234567890123456789012345678901!
Run with -h to get usage info.
```
> Make sure strncpy writes null-terminated strings

- README.md
- uhubctl.c
Hi,
we are currently developing a Linux based embedded device on which we want to be able to power on/off the individual USB ports.
Wiring up the on-board hub for individual port switching and using `uhubctl` as control software was thus an obvious choice.
We could however not get the desired reliability when turning ports off, even when using the retry parameter.
To solve this problem one of my colleagues has implemented [a sysfs interface to control the power status from userspace](https://lore.kernel.org/all/20220607114522.3359148-1-m.grzeschik@pengutronix.de/) which will land in the upcoming 6.0 Linux Kernel release.
We have since switched to using the sysfs directly to control port power instead of `uhubctl` in our own software, but would nevertheless like to see support for it in …
> Use sysfs interface on recent Linux kernels

- README.md
I tested `uhubctl` with my BenQ monitor and works without problems, this PR is just to add it to the compatibility list on the README.
> ADD: BenQ PD3220U monitor to compatibility list

- README.md
Revolution Pi Core and Connect family implement per port power switching for all USB ports.
NOTE: Connect 4 features a Renesas / NEC UPD720201 host controller, which acts as a root hub. Thus there is no "visible" vendor / product id, so I left the column empty.
> Add Revolution Pi to list of supported devices

- README.md
labgrid uses uhubctl in the USBPowerDriver to control power for boards connected on switchable USB hubs [1].
[1] https://github.com/labgrid-project/labgrid/blob/master/labgrid/driver/powerdriver.py
> Add labgrid to README as project using uhubctl

- uhubctl.c
Before:
```
Current status for hub 3 [6b1d:0200 Linux 6.1.98 xhci-hcd xHCI Host Controller 0000:01:00.0, USB 0.02, 2 ports, ppps]
Port 1: 0305 power lowspeed suspend connect [9911:c068 Sierra Wireless, Incorporated MC7304-CP]
Port 2: 0301 power lowspeed connect [0304:0160 FTDI FT232R USB UART A10OEDEW]
```
After:
```
Current status for hub 4 [1d6b:0003 Linux 6.1.98 xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 2 ports, ppps]
Port 1: 02a0 power 5gbps Rx.Detect
Port 2: 02a0 power 5gbps Rx.Detect
Current status for hub 3 [1d6b:0002 Linux 6.1.98 xhci-hcd xHCI Host Controller 0000:01:00.0, USB 2.00, 2 ports, ppps]
Port 1: 0503 power highspeed enable connect [1199:68c0 Sierra Wireless, Incorporated MC7304-CP]
Port 2: 0103 power enable connect [0403:6001 FTDI FT232R USB UART A10OEDEW] …
```
> Fix endian conversions to work for big-endian

- uhubctl.c
I need a feature to turn the specified port on and off after a specific delay,
The example below is to turn the port #1 at location 1-1.4 on and to turn it off after 1.5 second delay
```bash
uhubctl -d 1.5 -a flipoff -l 1-1.4 -p 1
```
> Add flipoff (inverted cycle) option - turn on and off

- uhubctl.c
Only the device specified by the given device path will be accessed, instead of scanning the USB bus.
Most useful if you use udev rules to create stable device node aliases for hubs, independent of bus topology.
For instance, if your matching udev rules include `SYMLINK+="MYSMARTHUB1"` you can call uhubctl with `--sysdev /dev/MYSMARTHUB1` instead of using `-l` and a non-stable bus location to specify it.
> Add --sysdev/-y option for direct device node access

- README.md
As I wrote in https://github.com/mvp/uhubctl/issues/630, the current version of ReTRY HUB may have a problem.
Although the current list of the compatible hubs is not wrong because it just talks about the previous version of ReTRY HUB, I want to add a note about the current version in order to prevent confusion.
> Add note to ReTRY HUB
